execute:
  echo: false
  warning: false
number-sections: true
number-depth: 2
number-offset: [0, 0]
format: 
  pdf: default
  html:
    embed-resources: true
    toc: true

editor_options: 
  chunk_output_type: console
  
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'