#' Residual-based posterior predictive metrics for longitudinal antibody curves
#'
#' Computes residuals between observed antibody measurements and posterior
#' median predictions evaluated at the observed time points. Returns pointwise
#' residuals or aggregated error metrics (MAE, RMSE, SSE) at multiple
#' summary levels.
#'
#' @param model A data frame of posterior draws in long format with columns:
#'   \code{Subject}, \code{Iso_type}, \code{Chain}, \code{Iteration},
#'   \code{Parameter}, \code{value}.
#' @param dataset A \code{serodynamics} case dataset produced by
#'   \code{serodynamics::as_case_data()} (must contain \code{id} and
#'   \code{antigen_iso} columns, and time/value attributes).
#' @param ids Character vector of subject IDs to include (matched against
#'   \code{dataset$id} and \code{model$Subject}).
#' @param antigen_iso Character scalar specifying the antigen/isotype to analyze
#'   (matched against \code{dataset$antigen_iso} and \code{model$Iso_type}).
#' @param scale Scale on which to compute residuals. One of \code{"original"}
#'   or \code{"log"}. If \code{"log"}, residuals are computed on the natural
#'   log scale and observations/predictions \eqn{\le 0} are removed.
#' @param summary_level Level at which to summarize metrics. One of:
#'   \describe{
#'     \item{\code{"pointwise"}}{
#'       Return pointwise residuals at each observed time point.
#'     }
#'     \item{\code{"id_antigen"}}{
#'       Summarize by \code{id} and \code{antigen_iso}.
#'     }
#'     \item{\code{"antigen"}}{Summarize by \code{antigen_iso} only.}
#'     \item{\code{"overall"}}{Single summary across all included observations.}
#'   }
#'
#' @return A tibble. For \code{summary_level = "pointwise"}, returns
#'   per-observation residuals. Otherwise returns MAE, RMSE, SSE, and
#'   \code{n_obs} at the requested summary level.
#'
#' @details
#' The posterior predictive summary uses the posterior median at each observed
#' time point, with a 95\% credible interval computed from draw-level
#' predictions. Predictions are generated by
#' \code{\link{predict_posterior_at_times}}.
#'
#' @examples
#' \dontrun{
#' # Per-ID error metrics (original scale)
#' m_id <- compute_residual_metrics(
#'   model = overall_sf2a,
#'   dataset = dL_clean_sf2a,
#'   ids = unique(dL_clean_sf2a$id),
#'   antigen_iso = "IgG",
#'   scale = "original",
#'   summary_level = "id_antigen"
#' )
#'
#' # Pointwise residuals on log scale
#' r_pw <- compute_residual_metrics(
#'   model = overall_sf2a,
#'   dataset = dL_clean_sf2a,
#'   ids = "SOSAR-22008",
#'   antigen_iso = "IgA",
#'   scale = "log",
#'   summary_level = "pointwise"
#' )
#' }
#'
#' @export
compute_residual_metrics <- function(model,
                                     dataset,
                                     ids,
                                     antigen_iso,
                                     scale = c("original", "log"),
                                     summary_level = c(
                                       "id_antigen",
                                       "pointwise",
                                       "antigen",
                                       "overall"
                                     )) {

  scale <- match.arg(scale)
  summary_level <- match.arg(summary_level)

  time_var  <- get_timeindays_var(dataset)
  value_var <- serocalculator::get_values_var(dataset)

  observed_data <- dataset |>
    dplyr::rename(
      t   = !!rlang::sym(time_var),
      obs = !!rlang::sym(value_var)
    ) |>
    dplyr::select(dplyr::all_of(c("id", "t", "obs", "antigen_iso"))) |>
    dplyr::mutate(id = as.character(.data$id)) |>
    dplyr::filter(.data$id %in% ids, .data$antigen_iso == antigen_iso)

  if (nrow(observed_data) == 0) {
    cli::cli_abort(
      "No observed data found for the specified IDs and antigen_iso."
    )
  }

  obs_times <- sort(unique(observed_data$t))

  predictions_all <- predict_posterior_at_times(
    model = model,
    ids = ids,
    antigen_iso = antigen_iso,
    times = obs_times
  )

  pred_summary <- predictions_all |>
    dplyr::summarise(
      .by = c("id", "t"),
      pred_med   = stats::median(.data$res, na.rm = TRUE),
      pred_lower = stats::quantile(.data$res, probs = 0.025, na.rm = TRUE),
      pred_upper = stats::quantile(.data$res, probs = 0.975, na.rm = TRUE)
    ) |>
    dplyr::mutate(id = as.character(.data$id))

  residual_data <- observed_data |>
    dplyr::inner_join(pred_summary, by = c("id", "t"))

  if (scale == "log") {
    residual_data <- residual_data |>
      dplyr::filter(.data$obs > 0, .data$pred_med > 0) |>
      dplyr::mutate(
        residual     = log(.data$obs) - log(.data$pred_med),
        abs_residual = abs(.data$residual),
        sq_residual  = .data$residual^2
      )
  } else {
    residual_data <- residual_data |>
      dplyr::mutate(
        residual     = .data$obs - .data$pred_med,
        abs_residual = abs(.data$residual),
        sq_residual  = .data$residual^2
      )
  }

  if (summary_level == "pointwise") {
    return(residual_data |>
      dplyr::select(
        "id",
        "antigen_iso",
        "t",
        "obs",
        "pred_med",
        "pred_lower",
        "pred_upper",
        "residual",
        "abs_residual",
        "sq_residual"
      ))
  }

  if (summary_level == "id_antigen") {
    return(residual_data |>
      dplyr::summarise(
        .by = c("id", "antigen_iso"),
        MAE = mean(.data$abs_residual, na.rm = TRUE),
        RMSE = sqrt(mean(.data$sq_residual, na.rm = TRUE)),
        SSE = sum(.data$sq_residual, na.rm = TRUE),
        n_obs = dplyr::n()
      ))
  }

  if (summary_level == "antigen") {
    return(residual_data |>
      dplyr::summarise(
        .by = "antigen_iso",
        MAE = mean(.data$abs_residual, na.rm = TRUE),
        RMSE = sqrt(mean(.data$sq_residual, na.rm = TRUE)),
        SSE = sum(.data$sq_residual, na.rm = TRUE),
        n_obs = dplyr::n()
      ))
  }

  residual_data |>
    dplyr::summarise(
      MAE = mean(.data$abs_residual, na.rm = TRUE),
      RMSE = sqrt(mean(.data$sq_residual, na.rm = TRUE)),
      SSE = sum(.data$sq_residual, na.rm = TRUE),
      n_obs = dplyr::n()
    )
}
