# Copy to .github/workflows/news.yaml in your repo.
name: Check NEWS.md Changelog

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  check:
    uses: Morrison-Lab/gha/.github/workflows/check-news.yml@v2
    # with:
    #   changelog: NEWS.md
